sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t phalu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phalu/docker-react npm run test
    
